version: '3.1'

volumes:
  postgres:
    driver: local

services:
  db:
    image: postgres:14
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    environment:
      POSTGRES_PASSWORD: musicbrainz
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
